name: Android CI/CD
on:
  push:
    branches:
      - fastlane_github_action
jobs:
#  CI:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#
#      - name: Setup ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: '2.7.2'
#          bundler-cache: true
#          working-directory: android
#
#      - name: Run unit test
#        uses: maierj/fastlane-action@v2.2.0
#        with:
#          lane: 'unit_test'
#          subdirectory: android
#
#      # fix it
##      - name: Run integration test test
##        uses: reactivecircus/android-emulator-runner@v2
##        with:
##          api-level: 29
##          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
##          script: 'flutter test integration_test'

  CD:
    runs-on: ubuntu-latest
#    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: run fastlane internal
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'beta'
          subdirectory: android
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}

#      - name: Setup emulator and run integration test
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
#          script: 'flutter test integration_test'

#only if test passed configure keystore
#      - name: Configure Keystore
#        run: |
#          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
#          echo "storeFile=upload-keystore.jks" >> key.properties
#          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
#          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
#          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
#        env:
#          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
#          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
#          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
#          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
#        working-directory: android

  #      - name: run fastlane internal
  #        uses: maierj/fastlane-action@v2.2.0
  #        with:
  #          lane: 'beta'
  #          subdirectory: android
  #        env:
  #          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}

#  unit-test:
#    runs-on: ubuntu-latest
#    needs: init-enviroment
#    steps:
#      - name: run fastlane test
#        uses: maierj/fastlane-action@v2.2.0
#        with:
#          lane: 'unit_test'
#          subdirectory: android
#
#  integration-test:
#    runs-on: ubuntu-latest
#    needs: init-enviroment
#    steps:
#      - name: Setup emulator
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
#          script: 'flutter test integration_test'