name: Test, Build and Release Android
on:
  push:
    branches:
      - fastlane_github_action
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
          working-directory: android

      - name: run fastlane internal
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'internal'
          subdirectory: android